apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: inventory
spec:
  selector:
    app: inventory-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32000
  type: NodePort
