version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: inventory
      # Uncomment and set these if you want authentication
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: examplepassword
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend/inventory_management_system
    container_name: frontend
    ports:
      - "80:80"
    env_file:
      - ./Frontend/inventory_management_system/.env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
