apiVersion: v1
kind: Service
metadata:
  name: mongo-Service
  namespace: inventory
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 32017 # This is the port on which the service will be exposed on each node
