apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-frontend
  namespace: inventory
labels:
  app: inventory-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-frontend
  template:
    metadata:
      labels:
        app: inventory-frontend
    spec:
      containers:
      - name: frontend
        image: madhan152001/inventory-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_BACKEND_URL
